version: '3.7'
services:
  tidalrr:
    container_name: tidalrr
    image: jacobroyquebec/tidalrr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - PUID=1000
      - PGID=1000
    ports:
      - 8587:8000
    volumes:
      - ./tidalrr/config:/app/config
      - /path/to/download/folder:/app/download
      - ./import:/app/import
      - /path/to/lidarr/folders:/path/to/lidarr/folders