version: '3.7'
services:
  tidalrr:
    container_name: tidalrr
    image: tidalrr
    restart: unless-stopped
    environment:
      - TZ=America/Toronto
      - PUID=501
      - PGID=501
    ports:
      - 3001:3001
    volumes:
      - "./config:/app/tidalrr/database/config"
      - "./download:/app/download"
      - "./import:/app/import"
      #- /path/to/lidarr/folders:/path/to/lidarr/folders
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock